# ----
# Site

title: Central Color Palette
url: "https://kungtiger.github.io"
baseurl: "/central-color-palette"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Documentation for Central Color Palette WordPress plugin.
social:
  name: Central Color Palette
  links:
    - https://github.com/kungtiger/central-color-palette

# -----
# Build

timezone: Etc/UTC
repository: kungtiger/central-color-palette
permalink: pretty
searchable: true

wordpress:
    plugin_version: 1.11
    plugin_url: https://wordpress.org/plugins/kt-tinymce-color-grid
    download_url: https://downloads.wordpress.org/plugin/kt-tinymce-color-grid.1.11.zip

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - nbproject/

collections:
  guides:
    title: Guides
    permalink: /guide/:name/
    output: true
  docs:
    title: Documentation
    permalink: /:categories/:name/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      script: php
      priority: 10
      since: "2.0"
      namespace: "kt_Central_Palette"
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

kramdown:
  entity_output: as_input
