title: Central Color Palette
logo: /assets/img/logo.png
description: Manage a site-wide central color palette for an uniform look'n'feel! Supports the new Block Editor, Theme Customizer and many themes and plugins.
